import { User } from 'better-auth';

export interface PMISPluginOptions {
  clientId: string;
  clientSecret: string;
  authorizationUrl: string;
  tokenUrl: string;
  userInfoUrl: string;
  scope?: string;

  /**
   * Default callback path generated by plugin
   * example: /auth/pmis/callback
   */
  callbackPath?: string;

  /**
   * UI redirect after login
   */
  successRedirect?: string;
}

export interface PMISUser {
  candidate_id: number;
  candidate_name: string;
  mobile: string;
  email: string;
}

export interface UserWithPhoneNumber extends User {
  phoneNumber: string;
  phoneNumberVerified: boolean;
  dateOfBirth?: string;
  isMinor?: boolean;
  termsAccepted: boolean | null;
  privacyAccepted: boolean | null;
}
